-- Project 3 Supabase schema migration
create extension if not exists vector with schema extensions;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  document_id text unique not null,
  title text not null,
  category text not null,
  storage_path text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  document_id text not null references public.documents(document_id) on delete cascade,
  parent_section text,
  child_index int not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(768),
  created_at timestamptz not null default now()
);

create table if not exists public.review_results (
  id bigint generated by default as identity primary key,
  document_id text not null,
  question text not null,
  answer text,
  risk_level text,
  citations jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists document_chunks_embedding_hnsw
on public.document_chunks using hnsw (embedding extensions.vector_cosine_ops);

create or replace function public.match_document_chunks(
  query_embedding extensions.vector(768),
  match_count int default 8,
  filter_category text default null
) returns table (
  id bigint,
  document_id text,
  parent_section text,
  content text,
  metadata jsonb,
  similarity float
) language sql stable
set search_path = public, extensions
as $$
  select dc.id, dc.document_id, dc.parent_section, dc.content, dc.metadata,
         1 - (dc.embedding <=> query_embedding) as similarity
  from public.document_chunks dc
  join public.documents d on d.document_id = dc.document_id
  where filter_category is null or d.category = filter_category
  order by dc.embedding <=> query_embedding
  limit match_count;
$$;
